"""empty message

Revision ID: 05cf809fa6b5
Revises: 4563b27cadc2
Create Date: 2022-06-03 17:14:11.550997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cf809fa6b5'
down_revision = '4563b27cadc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('device_id', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('execution_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('created', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('tasks', 'created')
    op.drop_column('tasks', 'execution_type')
    op.drop_column('tasks', 'device_id')
    # ### end Alembic commands ###
