"""empty message

Revision ID: 12d8f5ddd639
Revises: 767cb7c322ff
Create Date: 2022-08-03 20:36:53.210430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d8f5ddd639'
down_revision = '767cb7c322ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True),
        sa.Column('name', sa.String(), nullable=False),
    )
    op.create_unique_constraint("uq_id", "devices", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
