"""empty message

Revision ID: 1f3987bf643c
Revises: 557e56c599f1
Create Date: 2022-08-06 17:43:30.881126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3987bf643c'
down_revision = '557e56c599f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
