"""empty message

Revision ID: 21c59065236f
Revises: 8f1b5067f52e
Create Date: 2022-08-07 16:55:48.158077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c59065236f'
down_revision = '8f1b5067f52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_results', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_results', 'devices', ['device_id'], ['id'])
    op.drop_column('task_results', 'device_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_results', sa.Column('device_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_results', type_='foreignkey')
    op.drop_column('task_results', 'device_id')
    # ### end Alembic commands ###
