"""empty message

Revision ID: 30681d4e6996
Revises: 12d8f5ddd639
Create Date: 2022-08-03 21:50:32.179340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30681d4e6996'
down_revision = '12d8f5ddd639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('friendly_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'friendly_name')
    # ### end Alembic commands ###
