"""empty message

Revision ID: 557e56c599f1
Revises: 61f8930cf13b
Create Date: 2022-08-06 17:43:19.702368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557e56c599f1'
down_revision = '61f8930cf13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
