"""empty message

Revision ID: 61f8930cf13b
Revises: 30681d4e6996
Create Date: 2022-08-06 17:39:54.215490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f8930cf13b'
down_revision = '30681d4e6996'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE TYPE devicestatus AS ENUM('active', 'inactive')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('key', sa.String(), nullable=False))
    op.add_column('devices', sa.Column('status', sa.Enum('active', 'inactive', name='devicestatus'), server_default='active', nullable=True))
    op.alter_column('devices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_id', 'devices', type_='unique')
    op.drop_column('devices', 'friendly_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('friendly_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_id', 'devices', ['name'])
    op.alter_column('devices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'key')
    # ### end Alembic commands ###

    op.execute("DROP TYPE devicestatus")
