"""empty message

Revision ID: 6fffd04fafe2
Revises: 9d704360f361
Create Date: 2022-07-15 14:58:58.415759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fffd04fafe2'
down_revision = '9d704360f361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
