"""empty message

Revision ID: 767cb7c322ff
Revises: bca316e3ca32
Create Date: 2022-08-02 05:11:01.841922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '767cb7c322ff'
down_revision = 'bca316e3ca32'
branch_labels = None
depends_on = None

new_status = postgresql.ENUM('pending', 'done', 'not_supported', name='resultstatus')
old_status = postgresql.ENUM('pending', 'done', name='resultstatus')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE resultstatus ADD VALUE 'not_supported'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE resultstatus RENAME TO resultstatus_old")
    op.execute("CREATE TYPE resultstatus AS ENUM('pending', 'done')")
    op.execute((
        "ALTER TABLE task_results ALTER COLUMN status TYPE resultstatus USING "
        "status::text::resultstatus"
    ))
    op.execute("DROP TYPE resultstatus_old")
    # ### end Alembic commands ###
