"""empty message

Revision ID: 8f1b5067f52e
Revises: 1f3987bf643c
Create Date: 2022-08-06 19:43:28.146295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1b5067f52e'
down_revision = '1f3987bf643c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_results', sa.Column('device_key', sa.String(), nullable=False))
    op.drop_column('task_results', 'device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_results', sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task_results', 'device_key')
    # ### end Alembic commands ###
