"""empty message

Revision ID: 9d704360f361
Revises: 07b5165f4e84
Create Date: 2022-07-13 18:20:26.437230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d704360f361'
down_revision = '07b5165f4e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_params', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('tasks', 'sense_n_samples')
    op.drop_column('tasks', 'sense_metric')
    op.drop_column('tasks', 'sense_sample_rate')
    op.drop_column('tasks', 'sense_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sense_mode', postgresql.ENUM('single', 'max', 'min', 'average', name='sensemode'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('sense_sample_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('sense_metric', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('sense_n_samples', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'task_params')
    # ### end Alembic commands ###
