"""empty message

Revision ID: bca316e3ca32
Revises: 6fffd04fafe2
Create Date: 2022-07-19 22:12:27.059561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca316e3ca32'
down_revision = '6fffd04fafe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_results', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_results', 'completed_at')
    # ### end Alembic commands ###
